image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - export NODE_ENV=development
            - yarn
            - yarn build
          artifacts:
            - dist/**
      - step:
          script:
            - pipe: atlassian/aws-s3-deploy:0.2.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'eu-central-1'
                S3_BUCKET: $AWS_BUCKET_NAME
                LOCAL_PATH: 'dist'
                ACL: 'public-read'
                CACHE_CONTROL: 'max-age=3600'
                EXPIRES: '2019-03-12T00:00:00+00:00'
                DELETE_FLAG: 'true'
                EXTRA_ARGS: '--follow-symlinks --quiet'